name: 'Infra - Stage'

on:
  pull_request:
    branches:
    - stage

jobs:
  terraform:
    name: "Stage deploy"
    uses: "./.github/workflows/terraform-deploy.yaml"
    with:
      env: stage
      tf_state_bucket: cl-challenge-stage
      workload_identity_provider: projects/995096337479/locations/global/workloadIdentityPools/github-pool/providers/github-provider
      service_account: provisioner-sa-stage@provisioner-377821.iam.gserviceaccount.com
    secrets: inherit
