name: Infra - Deploy to production

on:
  workflow_dispatch:
    inputs:

jobs:
  terraform:
    name: "Prod deploy"
    uses: "./.github/workflows/terraform-deploy.yaml"
    with:
      env: prod
      tf_state_bucket: cl-challenge-prod
      workload_identity_provider: projects/995096337479/locations/global/workloadIdentityPools/github-pool/providers/github-provider
      service_account: provisioner-sa-prod@provisioner-377821.iam.gserviceaccount.com
    secrets: inherit